name: Monorepo CI/CD for Frontend & Backend with Conditional Build & Push
# Deployments to Railway

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # Check changes in frontend and backend to decide which one to build and deploy
  changes:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      backend: ${{ steps.filter.outputs.backend }}
    steps:
       - name: Checkout repository
         uses: actions/checkout@v4

       - name: Check for changes
         uses: dorny/paths-filter@v3
         id: filter
         with:
           filters: |
             frontend:
               - 'frontend/**'
             backend:
               - '*' 
               - '!frontend/**'

  # Build and Deploy Frontend (only if there are changes in frontend)
  deploy-frontend:
    needs: changes
    if: ${{ needs.changes.outputs.frontend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      
      - name: Build and Push Frontend
        uses: docker/build-push-action@v7
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}-frontend:latest
          build-args: 
            VITE_BACKEND_URL=${{ vars.VITE_BACKEND_URL }} # Included "https://" in 
      
      # Deploy Frontend to Railway
      # - name: Install Railway CLI
      #   run: npm install -g @railway/cli
         
      # - name: Link Railway Project
      #   run: railway link --project ${{ vars.RAILWAY_PROJECT_ID }} --environment production
      #   env:
      #     RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}

      # - name: Deploy/Redeploy Railway Service
      #   run: railway redeploy --service ${{ vars.RAILWAY_FRONTEND_SERVICE_ID }} --yes
      #   env: 
      #     RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}

  # Build and Deploy Backend (only if there are changes in backend or root)
  deploy-backend:
    needs: changes
    if: ${{ needs.changes.outputs.backend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      
      - name: Build and Push Backend
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}-backend:latest
      
      # Deploy Backend to Railway
      # - name: Install Railway CLI
      #   run: npm install -g @railway/cli

      # - name: Link Railway Project
      #   run: railway link --project ${{ vars.RAILWAY_PROJECT_ID }} --environment production
      #   env: 
      #     RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}

      # - name: Deploy/Redeploy Railway Service
      #   run: railway redeploy --service ${{ vars.RAILWAY_BACKEND_SERVICE_ID }} --yes
      #   env: 
      #     RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
